export default {
  LOGIN: "AUTH.LOGIN",
  LOGOUT: "AUTH.LOGOUT",
  HOME: "HOME",
  MANAGEMENT_USER: "MANAGEMENT.USER",
  MANAGEMENT_CATEGORY: "MANAGEMENT.CATEGORY",
  MANAGEMENT_INVOICE: "MANAGEMENT.INVOICE",
}